language: node_js

node_js:
  - "node"
  - "lts/*"

before_install:
  - npm install

script:
  - npm test:all-versions
  - npm run type:check
  - npm run prettier:check
  - npm run build
  - npm pack
